/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_User;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import service.Service_User;

/**
 *
 * @author Uhnuy Kozuki
 */
public class Form_GantiPassword extends javax.swing.JPanel {

    private Service_User servis = new DAO_User();
    
    public Form_GantiPassword() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRounded1 = new custom.PanelRounded();
        t_passwordBaru = new javax.swing.JPasswordField();
        t_passwordLama = new javax.swing.JPasswordField();
        t_username = new javax.swing.JTextField();
        t_passwordBaruKonfirmasi = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_submit = new custom.ButtonRounded();

        panelRounded1.setBackground(new java.awt.Color(255, 255, 255));
        panelRounded1.setRoundBottomLeft(50);
        panelRounded1.setRoundBottomRight(50);
        panelRounded1.setRoundTopLeft(50);
        panelRounded1.setRoundTopRight(50);

        t_passwordBaru.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_passwordBaru.setText("password");
        t_passwordBaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordBaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordBaruFocusLost(evt);
            }
        });

        t_passwordLama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_passwordLama.setText("password");
        t_passwordLama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordLamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordLamaFocusLost(evt);
            }
        });

        t_username.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_username.setText("username");
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });

        t_passwordBaruKonfirmasi.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_passwordBaruKonfirmasi.setText("password");
        t_passwordBaruKonfirmasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordBaruKonfirmasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordBaruKonfirmasiFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Pergantian Password");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Password Lama");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Password Baru");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Konfirmasi Password Baru");

        btn_submit.setText("SUBMIT");
        btn_submit.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRounded1Layout = new javax.swing.GroupLayout(panelRounded1);
        panelRounded1.setLayout(panelRounded1Layout);
        panelRounded1Layout.setHorizontalGroup(
            panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRounded1Layout.createSequentialGroup()
                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRounded1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRounded1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRounded1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_passwordBaru)
                            .addComponent(t_passwordLama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_passwordBaruKonfirmasi)
                            .addComponent(t_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRounded1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRounded1Layout.setVerticalGroup(
            panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRounded1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_passwordLama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_passwordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_passwordBaruKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRounded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRounded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String user=t_username.getText();
        if(user.equals("username")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String user=t_username.getText();
        if(user.equals("")||user.equals("username")){
            t_username.setText("username");

        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_passwordLamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordLamaFocusGained
        String user=t_passwordLama.getText();
        if(user.equals("password")){
            t_passwordLama.setText("");
        }
    }//GEN-LAST:event_t_passwordLamaFocusGained

    private void t_passwordLamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordLamaFocusLost
        String user=t_passwordLama.getText();
        if(user.equals("")||user.equals("passsword")){
            t_passwordLama.setText("passsword");

        }
    }//GEN-LAST:event_t_passwordLamaFocusLost

    private void t_passwordBaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordBaruFocusGained
        String user=t_passwordBaru.getText();
        if(user.equals("passsword")){
            t_passwordBaru.setText("");
        }
    }//GEN-LAST:event_t_passwordBaruFocusGained

    private void t_passwordBaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordBaruFocusLost
        String user=t_passwordBaru.getText();
        if(user.equals("")||user.equals("passsword")){
            t_passwordBaru.setText("passsword");

        }
    }//GEN-LAST:event_t_passwordBaruFocusLost

    private void t_passwordBaruKonfirmasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordBaruKonfirmasiFocusGained
        String user=t_passwordBaruKonfirmasi.getText();
        if(user.equals("password")){
            t_passwordBaruKonfirmasi.setText("");
        }
    }//GEN-LAST:event_t_passwordBaruKonfirmasiFocusGained

    private void t_passwordBaruKonfirmasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordBaruKonfirmasiFocusLost
        String user=t_passwordBaruKonfirmasi.getText();
        if(user.equals("")||user.equals("password")){
            t_passwordBaruKonfirmasi.setText("password");

        }
    }//GEN-LAST:event_t_passwordBaruKonfirmasiFocusLost

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        String username = t_username.getText();
        String oldPassword = t_passwordLama.getText();
        String newPassword = t_passwordBaru.getText();
        String konfirmasiPasswordBaru = t_passwordBaruKonfirmasi.getText();

        if (!newPassword.equals(konfirmasiPasswordBaru)) {
            JOptionPane.showMessageDialog(null, "Konfirmasi password baru tidak sesuai!");
            return;
        }

        if (!servis.validateOldPassword(username, oldPassword)) {
            JOptionPane.showMessageDialog(null, "Username dan Password lama tidak valid!");
            return;
        }

        if (servis.changePassword(username, oldPassword, newPassword)) {
            JOptionPane.showMessageDialog(null, "Password berhasil diubah!");
        } else {
            JOptionPane.showMessageDialog(null, "Password gagal diubah!");
        }
        resetForm();
    }//GEN-LAST:event_btn_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.ButtonRounded btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private custom.PanelRounded panelRounded1;
    private javax.swing.JPasswordField t_passwordBaru;
    private javax.swing.JPasswordField t_passwordBaruKonfirmasi;
    private javax.swing.JPasswordField t_passwordLama;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        t_username.setText("username");
        t_passwordLama.setText("password");
        t_passwordBaru.setText("password");
        t_passwordBaruKonfirmasi.setText("password");
    }
}
